general:
  dns:          dinamic1.cdmon.net
  email:        root@server
  log_level:    DEBUG
  service_url:  https://dinamico.cdmon.org/onlineService.php

users:
  cdmon_user:
    hosts: kandalf.com.ar blog.kandalf.com.ar
    md5pass: 1278323gfb37875f2749ju6cabd8io89

